// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CarrierCreate(arg1:dto.CarrierCreateReq):Promise<dto.Response_interface____>;

export function CarrierDelete(arg1:string):Promise<dto.Response_interface____>;

export function CarrierGet(arg1:string):Promise<dto.Response_mobile_locator_internal_dto_CarrierData_>;

export function CarrierList(arg1:string,arg2:number,arg3:number):Promise<dto.Response_mobile_locator_internal_dto_CarrierPageData_mobile_locator_internal_dto_CarrierData__>;

export function CarrierProcessCSV(arg1:string):Promise<dto.Response___uint8_>;

export function CarrierUpdate(arg1:string,arg2:dto.CarrierUpdateReq):Promise<dto.Response_interface____>;

export function SaveCSV(arg1:Array<number>):Promise<void>;
