// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CarrierCreate(arg1) {
  return window['go']['main']['App']['CarrierCreate'](arg1);
}

export function CarrierDelete(arg1) {
  return window['go']['main']['App']['CarrierDelete'](arg1);
}

export function CarrierGet(arg1) {
  return window['go']['main']['App']['CarrierGet'](arg1);
}

export function CarrierList(arg1, arg2, arg3) {
  return window['go']['main']['App']['CarrierList'](arg1, arg2, arg3);
}

export function CarrierProcessCSV(arg1) {
  return window['go']['main']['App']['CarrierProcessCSV'](arg1);
}

export function CarrierUpdate(arg1, arg2) {
  return window['go']['main']['App']['CarrierUpdate'](arg1, arg2);
}

export function SaveCSV(arg1) {
  return window['go']['main']['App']['SaveCSV'](arg1);
}
